/*
 * This file is generated by jOOQ.
 */
package edu.java.jooq.domain;


import edu.java.jooq.domain.tables.Chats;
import edu.java.jooq.domain.tables.LinkChat;
import edu.java.jooq.domain.tables.Links;
import edu.java.jooq.domain.tables.records.ChatsRecord;
import edu.java.jooq.domain.tables.records.LinkChatRecord;
import edu.java.jooq.domain.tables.records.LinksRecord;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatsRecord> CONSTRAINT_3 = Internal.createUniqueKey(Chats.CHATS, DSL.name("CONSTRAINT_3"), new TableField[] { Chats.CHATS.ID }, true);
    public static final UniqueKey<LinkChatRecord> CONSTRAINT_47 = Internal.createUniqueKey(LinkChat.LINK_CHAT, DSL.name("CONSTRAINT_47"), new TableField[] { LinkChat.LINK_CHAT.LINK_ID, LinkChat.LINK_CHAT.CHAT_ID }, true);
    public static final UniqueKey<LinksRecord> CONSTRAINT_4 = Internal.createUniqueKey(Links.LINKS, DSL.name("CONSTRAINT_4"), new TableField[] { Links.LINKS.ID }, true);
    public static final UniqueKey<LinksRecord> CONSTRAINT_45 = Internal.createUniqueKey(Links.LINKS, DSL.name("CONSTRAINT_45"), new TableField[] { Links.LINKS.URL }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<LinkChatRecord, LinksRecord> CONSTRAINT_470 = Internal.createForeignKey(LinkChat.LINK_CHAT, DSL.name("CONSTRAINT_470"), new TableField[] { LinkChat.LINK_CHAT.LINK_ID }, Keys.CONSTRAINT_4, new TableField[] { Links.LINKS.ID }, true);
    public static final ForeignKey<LinkChatRecord, ChatsRecord> CONSTRAINT_4702 = Internal.createForeignKey(LinkChat.LINK_CHAT, DSL.name("CONSTRAINT_4702"), new TableField[] { LinkChat.LINK_CHAT.CHAT_ID }, Keys.CONSTRAINT_3, new TableField[] { Chats.CHATS.ID }, true);
}
