/*
 * This file is generated by jOOQ.
 */
package edu.java.jooq.domain.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LinkChat implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long linkId;
    private Long chatId;
    private OffsetDateTime addedAt;

    public LinkChat() {}

    public LinkChat(LinkChat value) {
        this.linkId = value.linkId;
        this.chatId = value.chatId;
        this.addedAt = value.addedAt;
    }

    @ConstructorProperties({ "linkId", "chatId", "addedAt" })
    public LinkChat(
        @NotNull Long linkId,
        @NotNull Long chatId,
        @Nullable OffsetDateTime addedAt
    ) {
        this.linkId = linkId;
        this.chatId = chatId;
        this.addedAt = addedAt;
    }

    /**
     * Getter for <code>LINK_CHAT.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkId() {
        return this.linkId;
    }

    /**
     * Setter for <code>LINK_CHAT.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Long linkId) {
        this.linkId = linkId;
    }

    /**
     * Getter for <code>LINK_CHAT.CHAT_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getChatId() {
        return this.chatId;
    }

    /**
     * Setter for <code>LINK_CHAT.CHAT_ID</code>.
     */
    public void setChatId(@NotNull Long chatId) {
        this.chatId = chatId;
    }

    /**
     * Getter for <code>LINK_CHAT.ADDED_AT</code>.
     */
    @Nullable
    public OffsetDateTime getAddedAt() {
        return this.addedAt;
    }

    /**
     * Setter for <code>LINK_CHAT.ADDED_AT</code>.
     */
    public void setAddedAt(@Nullable OffsetDateTime addedAt) {
        this.addedAt = addedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final LinkChat other = (LinkChat) obj;
        if (this.linkId == null) {
            if (other.linkId != null)
                return false;
        }
        else if (!this.linkId.equals(other.linkId))
            return false;
        if (this.chatId == null) {
            if (other.chatId != null)
                return false;
        }
        else if (!this.chatId.equals(other.chatId))
            return false;
        if (this.addedAt == null) {
            if (other.addedAt != null)
                return false;
        }
        else if (!this.addedAt.equals(other.addedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.linkId == null) ? 0 : this.linkId.hashCode());
        result = prime * result + ((this.chatId == null) ? 0 : this.chatId.hashCode());
        result = prime * result + ((this.addedAt == null) ? 0 : this.addedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LinkChat (");

        sb.append(linkId);
        sb.append(", ").append(chatId);
        sb.append(", ").append(addedAt);

        sb.append(")");
        return sb.toString();
    }
}
