app:
  scheduler:
    enable: true
    interval: 10000
    force-check-delay: 10000

spring:
  application:
    name: scrapper

server:
  port: 8091

logging:
  config: classpath:log4j2-plain.xml

stackoverflow:
  base:
    url: https://api.stackexchange.com/2.3

github:
  base:
    url: https://api.github.com

bot:
  base:
    url: http://localhost:8090

springdoc:
  swagger-ui:
    path: /swagger-ui
  default-produces-media-type: application/json
