app:
  telegramToken: 6379106394:AAGx-SZur6HE-KEhKXSyT9MGSJoYnvfYGME
  telegramName: vf_scrapper_bot

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
