app:
  telegram-token: 6379106394:AAGvQhvEwr90rYWkoAp9RY4_lv16jIM_AGc
  telegram-name: vf_scrapper_bot

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

scrapper:
  base:
    url: http://localhost:8091

springdoc:
  swagger-ui:
    path: /swagger-ui
  default-produces-media-type: application/json
